### ISSUE TITLE
Documentation Required

### ISSUE THREAD

**Issue by gsteel** [laminas/laminas-i18n-phone-number#3]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes

#### Summary

Docs are currently absent… They should be present…

**Comment by froschdesign** [comment]
The files for the documentation will be added to this repository. But we do not create a separate documentation for this component, we will integrate it in [laminas-i18n](https://docs.laminas.dev/laminas-i18n/).

**Comment by gsteel** [comment]
Thanks @froschdesign 👍 - Closing
