### ISSUE TITLE
Documentation must be prepared

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas-i18n-phone-number#6]
The following topics must be covered and each must be presented on a separate page:

- Filters
  - ToE164
  - ToInternationalPhoneNumber
  - ToNationalPhoneNumber
- Validators
  - PhoneNumber
- View Helpers
  - PhoneNumberFormat

The configuration with `default-country-code` and `acceptable-number-types` should be implemented in the section ["Application Integration"](https://github.com/laminas/documentation/issues/8).

The content of the pages must follow the existing structure.

Examples:

- https://docs.laminas.dev/laminas-i18n/filters/alnum/
- https://docs.laminas.dev/laminas-i18n/validators/phone-number/
- https://docs.laminas.dev/laminas-i18n/view-helpers/currency-format/

---

Unfortunately, at the moment [we do not have an operational solution](https://github.com/jdoiro3/mkdocs-multirepo-plugin/issues/11) to merge documentations. ~Therefore, the new pages will be added to the repository of laminas-i18n – _temporary_.
(To ensure that the topic is not forgotten, the problem is followed up in a separate issue report.)~
Therefore we will use the [URL snippets extension of PyMdown](https://facelessuser.github.io/pymdown-extensions/extensions/snippets/#url-snippets).

The goal is still to keep information together for the reader. At the moment, a lot is fragmented and you have to search too much or coherent explanations are missing.
(Examples: [laminas-paginator and laminas-paginator-adapter-laminasdb](https://docs.laminas.dev/components/#navigation-and-pagination) or [Mezzio and authentication](https://docs.mezzio.dev/#authentication))

**Comment by froschdesign** [comment]
@gsteel 
I will help here.

**Comment by Ocramius** [comment]
Ah, I suppose this is still a blocker for `1.0.0`?

**Comment by froschdesign** [comment]
@Ocramius 
Correct!

**Comment by gsteel** [comment]
@froschdesign
So does this mean that docs can be setup in _this_ repo? If so, I can make a start on the docs in a new patch ASAP.

**Comment by Ocramius** [comment]
They should be maintained here, yep.

**Comment by froschdesign** [comment]
@gsteel 
> So does this mean that docs can be setup in _this_ repo?

Right, but only the content! No needed for MkDocs configuration here because the Markdown files will be inserted via the Snippets extension of the PyMdown Extensions in the documentation of laminas-i18n.

This means:

* create the folders `docs/book`
* add each validator, filter, view helper and form element in their related subfolder (see: https://github.com/laminas/laminas-i18n/tree/2.20.x/docs/book)
* each on a separate page / Markdown file

For reference see the documentation of laminas-i18n:

* [Alnum filter](https://docs.laminas.dev/laminas-i18n/filters/alnum/)
* [PhoneNumber validator](https://docs.laminas.dev/laminas-i18n/validators/phone-number/)
* [Date Format view helper](https://docs.laminas.dev/laminas-i18n/view-helpers/date-format/)

I recommend to use these pages as blueprints.
